server:
  port: 8082
spring:
  application:
    name: consul-client
  cloud:
    consul:
      host: 10.88.26.79
      port: 8500
      discovery:
        register: false
        # spring.cloud.consul.discovery.register需要配置成false，否则系统启动的时候，会向consul注册一个服务
ribbon:
  eager-load:
    clients:
    - tomcat
    enabled: true
